#include <stdio.h>
#include <stdbool.h>
#include <stdlib.h>

int Max(int a,int b)
{
	    return a>b?a:b;
}
int Min(int a,int b)
{
	    return a<b?a:b;
}
int main()
{
	    int x, y, n, D, h;
	        int matrix[1010][1010]={0,};
		    short num[100100]={0,};
		        scanf("%d %d %d",&x,&y,&n);

			    for(int i = 0 ; i < n ; i++){
				            scanf("%d",&D);
					            matrix[n-1-i][i] = D;
						            //max[i] = D;
							    //        num[D] = true;
							    //            }
							    //                for(int i = 0 ; i < n ; i++){
							    //                        for(int j = n-i ; j < n ; j++){
							    //                                    //matrix[i][j]는 matrix[i][j-1], matrix[i-1][j]보다 커야 함.
							    //                                                h = Max(matrix[i][j-1], matrix[i-1][j])+1;
							    //                                                            while(h <= y){
							    //                                                                            if(!num[h]){
							    //                                                                                                num[h]=true;
							    //                                                                                                                    matrix[i][j]=h;
							    //                                                                                                                                        break;
							    //                                                                                                                                                        }
							    //                                                                                                                                                                        h++;
							    //                                                                                                                                                                                    }
							    //                                                                                                                                                                                                if(h > y){
							    //                                                                                                                                                                                                                printf("infeasible\n");
							    //                                                                                                                                                                                                                                return 0;
							    //                                                                                                                                                                                                                                            }
							    //                                                                                                                                                                                                                                                    }
							    //                                                                                                                                                                                                                                                        }
							    //                                                                                                                                                                                                                                                            for(int i = n-1 ; i >= 0 ; i--){
							    //                                                                                                                                                                                                                                                                    for(int j = n-i-2 ; j >= 0 ; j--){
							    //                                                                                                                                                                                                                                                                                //matrix[i][j]는 matrix[i][j+1], matrix[i+1][j]보다 작아야 함.
							    //                                                                                                                                                                                                                                                                                            h = Min(matrix[i][j+1], matrix[i+1][j])-1;
							    //                                                                                                                                                                                                                                                                                                        while(h >= x){
							    //                                                                                                                                                                                                                                                                                                                        if(!num[h]){
							    //                                                                                                                                                                                                                                                                                                                                            num[h]=true;
							    //                                                                                                                                                                                                                                                                                                                                                                matrix[i][j]=h;
							    //                                                                                                                                                                                                                                                                                                                                                                                    break;
							    //                                                                                                                                                                                                                                                                                                                                                                                                    }
							    //                                                                                                                                                                                                                                                                                                                                                                                                                    h--;
							    //                                                                                                                                                                                                                                                                                                                                                                                                                                }
							    //                                                                                                                                                                                                                                                                                                                                                                                                                                            if(h < x){
							    //                                                                                                                                                                                                                                                                                                                                                                                                                                                            printf("infeasible\n");
							    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return 0;
							    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
							    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
							    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
							    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        for(int i = 0 ; i < n ; i++){
							    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                for(int j = 0 ; j < n ; j++){
							    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            printf("%d ",matrix[i][j]);
							    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
							    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            printf("\n");
							    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
							    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return 0;
							    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
							    //
